In [2]:
import numpy as np

a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a)
print(exp_a)

sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

y = exp_a / sum_exp_a
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


In [3]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a

In [4]:
a = np.array([1010, 1000, 990])
softmax(a)


/tmp/ipykernel_11972/1768208657.py:2: RuntimeWarning: overflow encountered in exp
  exp_a = np.exp(a)
/tmp/ipykernel_11972/1768208657.py:4: RuntimeWarning: invalid value encountered in divide
  y = exp_a / sum_exp_a


In [5]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c) # 오버플로우 방지용
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a

    return y

In [11]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)
print(np.sum(y))

[0.01821127 0.24519181 0.73659691]
1.0


In [12]:
a = np.array([1010, 1000, 990])
y = softmax(a)
print(y)
print(np.sum(y))

[9.99954600e-01 4.53978686e-05 2.06106005e-09]
1.0
